// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUzfClY3kRMEX4o7wL-yU-8Kt9xKyZGg8',
    appId: '1:895142114586:web:0e50359251b83a609268a3',
    messagingSenderId: '895142114586',
    projectId: 'notfile-378cb',
    authDomain: 'notfile-378cb.firebaseapp.com',
    databaseURL: 'https://notfile-378cb-default-rtdb.firebaseio.com',
    storageBucket: 'notfile-378cb.appspot.com',
    measurementId: 'G-QZLLE3DF3H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBM7Y_TiQBVa_wuLtsNarI71WMmXH2fbfA',
    appId: '1:895142114586:android:bf703898c9b266319268a3',
    messagingSenderId: '895142114586',
    projectId: 'notfile-378cb',
    databaseURL: 'https://notfile-378cb-default-rtdb.firebaseio.com',
    storageBucket: 'notfile-378cb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCc0ZfMwcufBk6oOvFhj6ajiQt9clwcyZk',
    appId: '1:895142114586:ios:2492d83e668aadf89268a3',
    messagingSenderId: '895142114586',
    projectId: 'notfile-378cb',
    databaseURL: 'https://notfile-378cb-default-rtdb.firebaseio.com',
    storageBucket: 'notfile-378cb.appspot.com',
    iosBundleId: 'com.example.not',
  );
}
